//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Granamiza.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoria
    {
        public categoria()
        {
            this.transacao = new HashSet<transacao>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public sbyte is_gasto { get; set; }
        public string icone { get; set; }
    
        public virtual ICollection<transacao> transacao { get; set; }

        public static implicit operator categoria(categoria v)
        {
            throw new NotImplementedException();
        }
    }
}
