//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Granamiza.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class granamizaEntities : DbContext
    {
        public granamizaEntities()
            : base("name=granamizaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<categoria> categoria { get; set; }
        public DbSet<cotacao> cotacao { get; set; }
        public DbSet<preferencias> preferencias { get; set; }
        public DbSet<simulacao> simulacao { get; set; }
        public DbSet<usuario> usuario { get; set; }
        public DbSet<transacao> transacao { get; set; }
        public DbSet<vwcategoriadespesa> vwcategoriadespesa { get; set; }
        public DbSet<vwcategoriareceita> vwcategoriareceita { get; set; }
    }
}
