//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Granamiza.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class preferencias
    {
        public int id { get; set; }
        public string avatar { get; set; }
        public sbyte dark_mode { get; set; }
        public sbyte transacao_email { get; set; }
        public sbyte email_verificado { get; set; }
        public int usuario_id { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
