//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Granamiza.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class simulacao
    {
        public int id { get; set; }
        public decimal valor_inserido { get; set; }
        public decimal juros { get; set; }
        public int qnt_meses { get; set; }
        public decimal aplicacoes_mensais { get; set; }
        public double rendimento_total { get; set; }
        public Nullable<System.DateTime> data_criacao { get; set; }
        public int usuario_id { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
