//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Granamiza.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class transacao
    {
        public int id { get; set; }
        public string descricao { get; set; }
        public decimal valor { get; set; }
        public SByte tipo_transacao { get; set; }
        public string data_insercao { get; set; }
        public string hora_insercao { get; set; }
        public System.DateTime data_criacao { get; set; }
        public int categoria_id { get; set; }
        public int usuario_id { get; set; }
    
        public virtual categoria categoria { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
